addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.15.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.14.0")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta43")
addSbtPlugin("dev.zio"        % "zio-sbt-ecosystem"   % "0.4.0-alpha.8")
addSbtPlugin("io.spray"       % "sbt-revolver"        % "0.10.0")